### ISSUE TITLE
when a plant is done i get this error

### ISSUE THREAD

**Issue by ClaireCruz** [SnappyDragon18/Snap-ons#13]
![unknown](https://user-images.githubusercontent.com/30986819/32471859-c1f0b914-c35f-11e7-8f4c-93136ce944df.png)
![unknownh](https://user-images.githubusercontent.com/30986819/32471860-c218e0e2-c35f-11e7-887e-650b1ba3b1ac.png)

please can you help me :(

**Comment by Cigh** [comment]
Hi, I encountered the same problem. I already created a pull request with a patch, but you can fix it yourself. 
In the line **511** (of the planttycoon.py file of course) change `await self.bot._send_message(discord.User(id=str(id)), message)` to `await self.bot.send_message(discord.User(id=str(id)), message)` and in **524** change `await self.bot._send_notification(gardener, message)` to `await self.bot.send_notification(gardener, message)`. Reload the cog and it should work.
